PBT - Enhancements
IINamelessII/forked-url-shrtnr-jedi-knights pull request #4
Opened 2021-03-26 20:18 UTC by AshenNagamaki

2021-03-26 20:20 UTC, AshenNagamaki commented
@dvasyab @yugisu QuickTheories library should be removed in the nearest future (unless, of course, used).

2021-03-27 11:14 UTC, IINamelessII requested changes

2021-03-27 11:14 UTC, IINamelessII commented on src/test/java/url/shortener/server/service/impl/UrlServiceImplTestPropertyBased.java
> +//  @BeforeEach
do not leave commented code wo a comment why it's needed
or just remove it pls

2021-03-27 11:15 UTC, AshenNagamaki commented on src/test/java/url/shortener/server/service/impl/UrlServiceImplTestPropertyBased.java
> +//  @BeforeEach
Got you.

2021-03-27 11:24 UTC, IINamelessII approved these changes

2021-03-27 11:26 UTC, dvasyab commented
As for me, that is all necessary changes that we had to done.

2021-03-27 11:26 UTC, dvasyab approved these changes

2021-03-27 11:27 UTC, IINamelessII approved these changes
Yes.

2021-03-27 11:27 UTC, yugisu approved these changes

2021-03-27 11:27 UTC, merged